apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: kpt-tech
description: main application pipeline
serialPipeline:
 stages:
 - targetId: kpt-tech
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: kpt-tech
description: development cluster
gke:
 cluster: projects/$PROJECT_ID/locations/us-central1/clusters/tech-kpt
