steps:
# Build and tag using commit sha
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'us-central1-docker.pkg.dev/searce-playground-v1/kpt-test-repo/kpt-image:${COMMIT_SHA}', '-f', 'Dockerfile']
# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/searce-playground-v1/kpt-test-repo/kpt-image:${COMMIT_SHA}']
# Create release in Google Cloud Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "kpt-tech",
      "--region", "asia-south1-a",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "kpt-tech=us-central1-docker.pkg.dev/searce-playground-v1/kpt-test-repo/kpt-image:${COMMIT_SHA}"
    ]
options:
 logging: CLOUD_LOGGING_ONLY
